### ISSUE TITLE
Unable to generate output

### ISSUE THREAD

**Issue by cybs-sue** [jason-fox/fox.jason.passthrough.swagger#1]
Hello Jason,

Thank you for creating this plug-in. I would love to use it. 

I'm running into a couple of issues and was wondering what I'm doing incorrectly on my end. 
I followed the install instructions. I'm on a Mac and used brew to install dita-ot and pandoc. 

I'm using: 
- The example Swagger petstore JSON as input.
- The sample bookmap you provided. I only added a chapter element to it. 
- This command to run the transform: dita --input=test.ditamap --format=pdf

The output I get: 
- I do see a PDF with the chapter content. 
- I get a blank page after the chapter. That's it. 

I look forward to hearing what it is I'm doing wrong. Thanks!

**Comment by jason-fox** [comment]
Its difficult to tell without some debug output.

Firstly try re-installing the **latest** versions of the plugin and its dependencies. There have been significant changes since the last accepted PR to the DITA-OT Plug-ins list.

```console
dita --install https://github.com/doctales/org.doctales.xmltask/archive/master.zip
dita --install https://github.com/jason-fox/fox.jason.passthrough/archive/master.zip
dita --install https://github.com/jason-fox/fox.jason.passthrough.pandoc/archive/master.zip
dita --install https://github.com/jason-fox/fox.jason.extend.css/archive/master.zip
dita --install https://github.com/jason-fox/fox.jason.passthrough.swagger/archive/master.zip
```

Blank page processing used to be the fallback for the passthrough plugins when erroring. This has been updated to fail with failure with an error message. Hopefully taking the latest tip and running in verbose (`-v`) or debug (`-d`) mode should expose some underlying issue.

```console
dita --input=test.ditamap --format=pdf -v > log.txt
```

I'm developing and testing on Mac and running unit tests on Unix so I should eventually work for you, as I know that Pet Store is a valid parseable file.

It would be helpful it you could attach your ditamap and log file to investigate further. Even better would be to create a Pull Request with your ditamap, dita and json.

**Comment by jason-fox** [comment]
This [test](https://github.com/jason-fox/fox.jason.passthrough.swagger/tree/master/test/pdf-local-file) already includes a swagger file and an extra chapter.

```console
dita \
  --input=dita/fox.jason.passthrough.swagger/test/pdf-local-file/document.ditamap \
  --format=pdf
```

**Comment by jason-fox** [comment]
> The sample bookmap you provided. I only added a chapter element to it.

If you are running the **PDF**  transform with a direct copy from the `README.md`. The Appendix will not be rendered since `print="no"` has been set on the `<appendices>` element:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap>
    ...etc
    <appendices toc="yes" print="no">
      <topicmeta>
        <navtitle>Appendices</navtitle>
      </topicmeta>
      <appendix format="swagger" href="Swagger_Definition.json"/>
   </appendices>
</bookmap>
```

For further information check the DITA standard on [printing](https://docs.oasis-open.org/dita/v1.2/os/spec/archSpec/printing.html)

**Comment by sjacobs-indeed** [comment]
Thank you for the test. When I run it, I get an error. It could be an issue with the swagger file in that folder. 

However, the great news is that the issue was very simple. It turns out the appendices attribute print="no" was the cause. Thanks for pointing that out. Sorry I missed it. This is great.

**Comment by cybs-sue** [comment]
Thank you! It turns out the appendices attribute print="no" was the cause. Thanks for pointing that out. Sorry I missed it. This is great. 

(Also, thank you for the test. When I run it, I get an error. It could be an issue with the swagger file in that folder.)

**Comment by jason-fox** [comment]
What is the error you are getting?

**Comment by cybs-sue** [comment]
This is the error I get when I run your test files as-is: 
Error: Failed to run pipeline: [DOTJ012F][FATAL] Failed to parse the input file 'file:/Users/s.../dita%20test/document.ditamap'.: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

BTW: Is there a way to convert Swagger to dita XML using this plug-in?

**Comment by jason-fox** [comment]
Just use the normalized DITA transform - a.k.a [DITA 2 DITA](https://www.dita-ot.org/3.3/topics/dita2dita.html)

```console
dita --input=test.ditamap --format=dita -v 
```

It should work on Mac, still tweaking the Window processsing - see https://github.com/jason-fox/fox.jason.passthrough/issues/1

**Comment by jason-fox** [comment]
DOTJ012F can be found in the [DITA Error Messages](https://www.dita-ot.org/3.3/topics/dita-messages) - 

> This message may indicate an invalid input file (such as accidentally specifying a PDF file as input rather than a DITA map file), an input file that uses elements which are not allowed, are not part or a DITA file that has errors and cannot be parsed as XML. You could also be using a specialized DITA document type that needs external plug-ins in order to be parsed correctly. The message issued by the XML parser should provide additional information to help diagnose the cause.

**Comment by cybs-sue** [comment]
Thanks for the updated command that transforms the swagger to dita. I'm having trouble opening the transformed dita file in Framemaker. This could be because the structured app I'm using does not follow the standard dita schema. 

Regarding the error message I'm getting from the example, I thought I used everything in the example and the correct command. So, I wanted to let you know that there might be something wrong with one of the source files in the example. However, if it's working for you, then I'm likely causing that error somewhere. 

I've been using a Mac, so I haven't had issues, but I would like to use your plug-in on Windows. So, thank you for working on that. I appreciate your help and quick responses.

**Comment by aidanreilly** [comment]
So I cleaned out and installed as follows:

    dita --install https://github.com/doctales/org.doctales.xmltask/archive/master.zip
    dita --install https://github.com/jason-fox/fox.jason.passthrough/archive/master.zip
    dita --install https://github.com/jason-fox/fox.jason.passthrough.pandoc/archive/master.zip
    dita --install https://github.com/jason-fox/fox.jason.extend.css/archive/master.zip
    dita --install https://github.com/jason-fox/fox.jason.passthrough.swagger/archive/master.zip

This completes successfully, 

    dita -i C:\dita-ot-3.5.2\plugins\fox.jason.passthrough.swagger\test\output-html\document.ditamap -f html5

This fails: 

    dita -i C:\dita-ot-3.5.2\plugins\fox.jason.passthrough.swagger\test\swagger-complex\document.ditamap -f html5

Error: 

	[swagger-gen] Java Result: 1
	[swagger-gen] Exception in thread "main" java.lang.NullPointerException
	[swagger-gen]   at io.github.swagger2markup.internal.component.ResponseComponent.lambda$apply$1(ResponseComponent.java:104)
	[swagger-gen]   at java.util.TreeMap.forEach(TreeMap.java:1005)
	[swagger-gen]   at io.github.swagger2markup.internal.component.ResponseComponent.apply(ResponseComponent.java:88)
	[swagger-gen]   at io.github.swagger2markup.internal.component.PathOperationComponent.buildResponsesSection(PathOperationComponent.java:233)
	[swagger-gen]   at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:112)
	[swagger-gen]   at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:236)
	[swagger-gen]   at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:220)
	[swagger-gen]   at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$0(PathsDocument.java:120)
	[swagger-gen]   at java.util.ArrayList.forEach(ArrayList.java:1257)
	[swagger-gen]   at io.github.swagger2markup.internal.document.PathsDocument.buildsPathsSection(PathsDocument.java:120)
	[swagger-gen]   at io.github.swagger2markup.internal.document.PathsDocument.apply(PathsDocument.java:104)
	[swagger-gen]   at io.github.swagger2markup.Swagger2MarkupConverter.applyPathsDocument(Swagger2MarkupConverter.java:201)
	[swagger-gen]   at io.github.swagger2markup.Swagger2MarkupConverter.toFile(Swagger2MarkupConverter.java:244)
	[swagger-gen]   at io.github.swagger2markup.cli.Application.run(Application.java:84)
	[swagger-gen]   at io.github.swagger2markup.cli.Application.main(Application.java:61)
	Error: The following error occurred while executing this line:
	C:\dita-ot-3.5.2\plugins\fox.jason.passthrough\resource\antlib.xml:23: The following error occurred while executing this line:
	C:\dita-ot-3.5.2\plugins\fox.jason.passthrough\resource\antlib.xml:55: The following error occurred while executing this line:
	C:\dita-ot-3.5.2\plugins\fox.jason.passthrough\resource\antlib.xml:67: The following error occurred while executing this line:
	C:\dita-ot-3.5.2\plugins\fox.jason.passthrough\resource\antlib.xml:74: The following error occurred while executing this line:
	C:\dita-ot-3.5.2\plugins\fox.jason.passthrough\resource\antlib.xml:148: The following error occurred while executing this line:
	jar:file:/C:/dita-ot-3.5.2/plugins/fox.jason.passthrough.swagger/lib/passthrough.swagger-1.1.jar!/fox/jason/swagger/antlib.xml:63: [SWAG001F][FATAL] SwaggerGen failed to generate documentation: C:/dita-ot-3.5.2/plugins/fox.jason.passthrough.swagger/test/swagger-complex/swagger.json. Check that your swagger file is valid.
